### ISSUE TITLE
AttributeError: 'str' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by rohanday3** [Kn0wn-Un/Auto-Zoom#1]
C:\Users\rohan\Downloads\Auto-Zoom-master>python Auto.py
Traceback (most recent call last):
  File "Auto.py", line 123, in <module>
    temp = curmeeting[0].timestamp()
AttributeError: 'str' object has no attribute 'timestamp'

[List - Copy.xlsx](https://github.com/Kn0wn-Un/Auto-Zoom/files/4642910/List.-.Copy.xlsx)

**Comment by Kn0wn-Un** [comment]
### Thank You 
**Sorry for replying so late my notifications were off**

The Problem is the date column in your excel is not formatted for date you can either:
1. Use the given excel sheet
2. format the date column of your own excel sheet like this https://imgur.com/zHom9GG

**Comment by rohanday3** [comment]
Okay, thanks

**Comment by gouravkhunger** [comment]
Could not resolve using the solution provided. Still that problem persists. Any Ideas?
