### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by riyulex** [Kn0wn-Un/Auto-Zoom#3]
I saw this code and I need help, for me is a little different, because my school changes every class the ID there’s a website of our school and there they put the link a few minutes before the class starts so it’s a little difficult to me use that code like there is right now, so a ask for you, if you can help me

**Comment by riyulex** [comment]
And in this website there is a Username and password to enter but each student have yours, so I have mine, if anyone with good heart can help me

**Comment by Kn0wn-Un** [comment]
I guess you ll have to find another script to take username and password from your website, and put it into the excel sheet.
