### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by PheelaV** [Kn0wn-Un/Auto-Zoom#5]
Hiya, first of thank you, I have downloaded and modified your script to make it work for my use case and it is great. I would like to contribute/publish modifications. Have you thought about adding a license?

**Comment by Kn0wn-Un** [comment]
Hi @PheelaV , thank you for your interest tbh I don't know much about licenses can you help me out?

**Comment by Kn0wn-Un** [comment]
Added MIT license feel free to modify.
