### ISSUE TITLE
    temp = curmeeting[0].timestamp() AttributeError: 'str' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by karimk123** [Kn0wn-Un/Auto-Zoom#9]
I get this error whenever i run the program, and I installed evverything, setup the excel sheet so i dont know what's wrong

**Comment by Kn0wn-Un** [comment]
The Problem is the date column in your excel is not formatted for date you can either:
1. Use the given excel sheet
2. format the date column of your own excel sheet like this https://imgur.com/zHom9GG
